### ISSUE TITLE
Analyze sentiment on a given text or bag-of-words

### ISSUE THREAD

**Issue by ffrankies** [ffrankies/reddit_seer#4]
Considerations:
- Most likely, will be using the actual text, not bag-of-words
- Need to be careful with the libraries we use, since most of them just do a simple `num_positive_words - num_negative_words` calculation
- May be possible to do more complex sentiment analysis, such as extracting emotions

**Comment by BoyInTheBoat** [comment]
I'm working on this currently. Don't know how to mark that I've taken it on.
